# Generated by Django 2.2 on 2022-08-22 00:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2022, 8, 22, 0, 41, 2, 633, tzinfo=utc), verbose_name='created time')),
                ('comments', models.CharField(max_length=200, verbose_name='comment contents')),
            ],
            options={
                'verbose_name': 'Course Comments',
                'verbose_name_plural': 'Course Comments',
            },
        ),
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2022, 8, 22, 0, 41, 2, 633, tzinfo=utc), verbose_name='created time')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('mobile', models.CharField(max_length=11, verbose_name='phone number')),
                ('course_name', models.CharField(max_length=50, verbose_name='course name')),
            ],
            options={
                'verbose_name': 'User Ask',
                'verbose_name_plural': 'User Ask',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2022, 8, 22, 0, 41, 2, 633, tzinfo=utc), verbose_name='created time')),
            ],
            options={
                'verbose_name': 'Courses that Users Have Studied',
                'verbose_name_plural': 'Courses that Users Have Studied',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2022, 8, 22, 0, 41, 2, 633, tzinfo=utc), verbose_name='created time')),
                ('fav_id', models.IntegerField(verbose_name='data id')),
                ('fav_type', models.IntegerField(choices=[(1, 'course'), (2, 'course organization'), (3, 'instructor')], default=1, verbose_name='favorite/saved type')),
            ],
            options={
                'verbose_name': 'User Favorite',
                'verbose_name_plural': 'User Favorite',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2022, 8, 22, 0, 41, 2, 633, tzinfo=utc), verbose_name='created time')),
                ('message', models.CharField(max_length=200, verbose_name='message contents')),
                ('has_read', models.BooleanField(default=False, verbose_name='if the message has read')),
            ],
            options={
                'verbose_name': 'User Message',
                'verbose_name_plural': 'User Message',
            },
        ),
    ]
