# Generated by Django 2.2 on 2022-08-16 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecomments',
            options={'verbose_name': 'Course Comments', 'verbose_name_plural': 'Course Comments'},
        ),
        migrations.AlterModelOptions(
            name='userask',
            options={'verbose_name': 'User Ask', 'verbose_name_plural': 'User Ask'},
        ),
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': 'Courses that Users Have Studied', 'verbose_name_plural': 'Courses that Users Have Studied'},
        ),
        migrations.AlterModelOptions(
            name='userfavorite',
            options={'verbose_name': 'User Favorite', 'verbose_name_plural': 'User Favorite'},
        ),
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': 'User Message', 'verbose_name_plural': 'User Message'},
        ),
    ]
