# Generated by Django 2.2 on 2022-08-22 00:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2022, 8, 22, 0, 41, 2, 633, tzinfo=utc), verbose_name='created time')),
                ('name', models.CharField(max_length=20, verbose_name='City Name')),
                ('desc', models.CharField(max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'city',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2022, 8, 22, 0, 41, 2, 633, tzinfo=utc), verbose_name='created time')),
                ('name', models.CharField(max_length=50, verbose_name='Course Organization Name')),
                ('desc', models.TextField(verbose_name='Organization Description')),
                ('tag', models.CharField(default='Most Popular', max_length=15, verbose_name='Organization Tag')),
                ('category', models.CharField(choices=[('pxjg', 'Bootcamp'), ('gr', 'Personal Instructor'), ('gx', 'University')], default='pxjg', max_length=20, verbose_name='Organization Category')),
                ('click_nums', models.IntegerField(default=0, verbose_name='Number of Views')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='Number of Favorite')),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='Org Logo')),
                ('address', models.CharField(max_length=150, verbose_name='Org Address')),
                ('students', models.IntegerField(default=0, verbose_name='Number of Students')),
                ('course_nums', models.IntegerField(default=0, verbose_name='Number of Courses')),
                ('is_auth', models.BooleanField(default=False, verbose_name='if certificated')),
                ('is_gold', models.BooleanField(default=False, verbose_name='if get best award')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.City', verbose_name='Currently Located City')),
            ],
            options={
                'verbose_name': 'Course Organization',
                'verbose_name_plural': 'Course Organization',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2022, 8, 22, 0, 41, 2, 633, tzinfo=utc), verbose_name='created time')),
                ('name', models.CharField(max_length=50, verbose_name='Teacher Name')),
                ('work_years', models.IntegerField(default=0, verbose_name='Teacher Working Years')),
                ('work_company', models.CharField(max_length=50, verbose_name='Teacher Company')),
                ('work_position', models.CharField(max_length=50, verbose_name='Teacher Title')),
                ('points', models.CharField(max_length=50, verbose_name='Teacher Key Features')),
                ('click_nums', models.IntegerField(default=0, verbose_name='Number of Views in Total')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='Number of Favorites in Total')),
                ('age', models.IntegerField(default=18, verbose_name='Age')),
                ('image', models.ImageField(upload_to='teacher/%Y/%m', verbose_name='Avatar')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='Affiliated Org')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teacher',
            },
        ),
    ]
