# Generated by Django 2.2 on 2022-08-22 00:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2022, 8, 22, 0, 41, 2, 633, tzinfo=utc), verbose_name='created time')),
                ('name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('desc', models.CharField(max_length=300, verbose_name='Course Description')),
                ('learn_times', models.IntegerField(default=0, verbose_name='Learning Hours (in mins)')),
                ('degree', models.CharField(choices=[('cj', 'Elementary Level'), ('zj', 'Intermediate Level'), ('gj', 'Advanced Level')], max_length=2, verbose_name='Difficulty Level')),
                ('students', models.IntegerField(default=0, verbose_name='Student Numbers')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='Number of Favorites')),
                ('click_nums', models.IntegerField(default=0, verbose_name='Number of Views')),
                ('notice', models.CharField(default='', max_length=300, verbose_name='Course Announcement')),
                ('category', models.CharField(default='Backend Development', max_length=20, verbose_name='Course Category')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='Course Tags')),
                ('youneed_know', models.CharField(default='', max_length=300, verbose_name='Course Notes')),
                ('teacher_tell', models.CharField(default='', max_length=300, verbose_name='Instructor Words')),
                ('is_classics', models.BooleanField(default=False, verbose_name='If a Featured Course')),
                ('detail', models.TextField(verbose_name='Course Details')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='Cover Pic')),
                ('course_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='course organization')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='Instructor')),
            ],
            options={
                'verbose_name': 'Course Info',
                'verbose_name_plural': 'Course Info',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2022, 8, 22, 0, 41, 2, 633, tzinfo=utc), verbose_name='created time')),
                ('name', models.CharField(max_length=100, verbose_name='Chapter Title')),
                ('learn_time', models.IntegerField(default=0, verbose_name='Learning Hours in Mins')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'verbose_name': 'Lesson Chapters',
                'verbose_name_plural': 'Lesson Chapters',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2022, 8, 22, 0, 41, 2, 633, tzinfo=utc), verbose_name='created time')),
                ('name', models.CharField(max_length=100, verbose_name='Video Name')),
                ('learn_times', models.IntegerField(default=0, verbose_name='Learning Hours in Mins')),
                ('url', models.CharField(max_length=200, verbose_name='Video Url')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='Chapter Name')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Video',
            },
        ),
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2022, 8, 22, 0, 41, 2, 633, tzinfo=utc), verbose_name='created time')),
                ('tag', models.CharField(max_length=100, verbose_name='标签')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程标签',
                'verbose_name_plural': '课程标签',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2022, 8, 22, 0, 41, 2, 633, tzinfo=utc), verbose_name='created time')),
                ('name', models.CharField(max_length=100, verbose_name='Course Name')),
                ('file', models.FileField(max_length=200, upload_to='course/resource/%Y/%m', verbose_name='Download Url')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'verbose_name': 'Course Resources',
                'verbose_name_plural': 'Course Resources',
            },
        ),
    ]
