# Generated by Django 2.2 on 2022-08-12 21:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='created time')),
                ('name', models.CharField(max_length=50, verbose_name='course name')),
                ('desc', models.CharField(max_length=300, verbose_name='course description')),
                ('learn_times', models.IntegerField(default=0, verbose_name='learning hours (in mins)')),
                ('degree', models.CharField(choices=[('cj', 'elementary level'), ('zj', 'intermediate level'), ('gj', 'advanced level')], max_length=2, verbose_name='difficulty level')),
                ('students', models.IntegerField(default=0, verbose_name='student numbers')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='number of saved')),
                ('click_nums', models.IntegerField(default=0, verbose_name='number of views')),
                ('notice', models.CharField(default='', max_length=300, verbose_name='course announcement')),
                ('category', models.CharField(default='Backend Development', max_length=20, verbose_name='course category')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='course tags')),
                ('youneed_know', models.CharField(default='', max_length=300, verbose_name='course notes')),
                ('teacher_tell', models.CharField(default='', max_length=300, verbose_name='instructor words')),
                ('detail', models.TextField(verbose_name='course details')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='cover pic')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='instructor')),
            ],
            options={
                'verbose_name': 'class info',
                'verbose_name_plural': 'class info',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='created time')),
                ('name', models.CharField(max_length=100, verbose_name='chapter title')),
                ('learn_time', models.IntegerField(default=0, verbose_name='learning hours in mins')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'verbose_name': 'lesson chapters',
                'verbose_name_plural': 'lesson chapters',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='created time')),
                ('name', models.CharField(max_length=100, verbose_name='video name')),
                ('learn_times', models.IntegerField(default=0, verbose_name='learning hours in mins')),
                ('url', models.CharField(max_length=200, verbose_name='video url')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='chapter name')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'video',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='created time')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('file', models.FileField(max_length=200, upload_to='course/resource/%Y/%m', verbose_name='download url')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'verbose_name': ' course resources',
                'verbose_name_plural': ' course resources',
            },
        ),
    ]
