# Generated by Django 2.2 on 2022-08-22 01:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetag',
            options={'verbose_name': 'Course Tags', 'verbose_name_plural': 'Course Tags'},
        ),
        migrations.AlterField(
            model_name='course',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 1, 21, 0, 120588, tzinfo=utc), verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 1, 21, 0, 120588, tzinfo=utc), verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='coursetag',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='coursetag',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 1, 21, 0, 120588, tzinfo=utc), verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='coursetag',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 1, 21, 0, 120588, tzinfo=utc), verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 1, 21, 0, 120588, tzinfo=utc), verbose_name='created time'),
        ),
    ]
